# build an executable named myprog from aa.out
all: unhappy.cpp
	rm myout.solution
	g++ -pthread -g -std=c++11 -o aa.out unhappy.cpp && echo 'run like ./aa.out < unhappy.judge > myout.solution'
 
clean:
	$(RM) aa.out
  
